# Generated by Django 5.0.14 on 2026-02-10 18:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeocodeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_text",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "normalized_text",
                    models.CharField(
                        help_text="Lowercased/Stripped for matching", max_length=255
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(help_text="OPIS Truckstop ID")),
                ("name", models.TextField()),
                ("address", models.TextField()),
                ("city", models.TextField()),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                ("retail_price", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "geocode_source",
                    models.CharField(
                        blank=True, default="census", max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "opis_id"], name="routing_fue_state_7e29be_idx"
                    ),
                    models.Index(
                        fields=["opis_id"], name="routing_fue_opis_id_b31c27_idx"
                    ),
                ],
            },
        ),
    ]
